Repository flavorjones/calendar-assistant, pull requests merged in 2019-02, with the labels that each got.

#99 95 exceptions are specific
  lib/calendar_assistant/event_repository.rb
  lib/calendar_assistant/location_config_validator.rb
Labels: state/needs-review

#100 aruba wants us to use `run_command` instead of `run`
  spec/calendar_assistant/cli/features/avail_spec.rb
  spec/calendar_assistant/cli/features/join_spec.rb
  spec/calendar_assistant/cli/features/lint_spec.rb
  spec/calendar_assistant/cli/features/location_spec.rb
  spec/calendar_assistant/cli/features/show_spec.rb
  spec/calendar_assistant/cli/features/utilities_spec.rb
Labels: state/needs-review

#96 launch zoom meetings directly with the zoom cli
  CHANGELOG.md
  lib/calendar_assistant.rb
  lib/calendar_assistant/cli/printer.rb
  lib/calendar_assistant/extensions/launchy_extensions.rb
  spec/calendar_assistant/cli/printer_spec.rb
  spec/calendar_assistant/extensions/launchy_extensions_spec.rb
Labels: state/needs-review

#103 aruba run_command needs at least v 14.8
  calendar-assistant.gemspec
Labels: state/needs-review

#102 add a badge for gem version
  README.md
Labels: state/needs-review

#105 Extract availability from event
  lib/calendar_assistant.rb
  lib/calendar_assistant/available_block.rb
  lib/calendar_assistant/event.rb
  lib/calendar_assistant/event_repository.rb
  lib/calendar_assistant/event_set.rb
  lib/calendar_assistant/has_duration.rb
  spec/calendar_assistant/available_block_spec.rb
  spec/calendar_assistant/event_repository_spec.rb
  spec/calendar_assistant/event_spec.rb
  spec/calendar_assistant/has_duration_spec.rb
  spec/shared_examples/an_object_that_has_duration.rb
  spec/spec_helper.rb
Labels: state/in-review

#94 50 test readme gen
  README.md
  README.md.erb
  Rakefile
  bin/calendar-assistant
  concourse/images/Dockerfile
  concourse/tasks/rake-spec/run.sh
  generate-readme
Labels: state/in-progress

#110 CA has interactive shell to improve load times, experience
  CHANGELOG.md
  README.md
  README.md.erb
  calendar-assistant.gemspec
  lib/calendar_assistant/cli.rb
  lib/calendar_assistant/cli/commands.rb
  spec/calendar_assistant/cli/commands_spec.rb
Labels: state/needs-review
